export const SCENE_KEYS = Object.freeze({
    PRELOAD_SCENE: "PRELOAD_SCENE",
    INTRO_SCENE: "INTRO_SCENE",
    MAIN_SCENE: "MAIN_SCENE",
    HUT_SCENE: "HUT_SCENE",
    FISHING_SCENE: "FISHING_SCENE",
    MISSING_SCENE: "MISSING_SCENE",
    FORESTY_ROAD: "FORESTY_ROAD"
})